import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google"
;
import "./globals.css";
import { WalletContextProvider } from "./components/WalletContextProvider";
import { AppBar } from "./components/AppBar";
import SolanaBalance from "./components/SolanaBalance";

const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Solana Token Mint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={archivo.className}>
        <WalletContextProvider>
          <AppBar />
          <SolanaBalance />
          {children}
        </WalletContextProvider>
      </body>
    </html>
  );
}